@baseUrl = http://localhost:3000

##########################################
### Cadastrando o cliente
##########################################

POST {{baseUrl}}/client
Content-Type: application/json

{
  "name": "João",
  "identifier": "123456789"
}

##########################################
### Atualizando dados de cliente já cadastrando
##########################################

PUT {{baseUrl}}/client/1
Content-Type: application/json

{
  "name": "João Victor",
  "identifier": "19971701182"
}

##########################################
### Buscar produtos de tal tipo

GET {{baseUrl}}/product/search?name=camisa

##########################################
### Busca produtos que estejam avaliados

GET {{baseUrl}}/product/get-available

##########################################
### Buscar um produto específico pelo id
#########################################

GET {{baseUrl}}/product/get-by-id/2

########################################
### Rota que faz operações de pedido sendo criação, adição de produtos dentro de um pedido e confirmação dele
########################################

POST {{baseUrl}}/order/process-confirm
Content-Type: application/json

{
  "action": "confirm",
  "order_id": 6
}

#########################################
### Buscar pedido por client
#########################################

GET {{baseUrl}}/order/get-by-client/1